version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: flay_away
    ports:
      - "5436:5436"
    environment:
      POSTGRES_DB: flay_away
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
